sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-us-east-1.aliyuncs.com
    access-key-id: LTAI5tAbM3wxneZbwbv9SKkF
    access-key-secret: 1CGJOQY099ZBCvr4LP437Mectd5YB0
    bucket-name: foodie-sky-take-out

  redis:
    host:localhost
    port:6379
    database:10